version: '3'
services:
  nginx:
    build: ./nginx/
    volumes:
      - /var/www/ufopensource:/data/letsencrypt
      - /etc/letsencrypt:/etc/letsencrypt
      - ./club-website/website:/website
    ports:
      - 80:80
      - 443:443
